### ISSUE TITLE
基于Beacon的通信

### ISSUE THREAD

**Issue by lanyan520** [dingjikerbo/BluetoothKit#1]
1.发现刚连接一秒后就自动断开了，而客户端发送数据显示发送成功了
2.需求：连接后发送数据等待回复json，是不是write和read方法同时调用就可以了

**Comment by dingjikerbo** [comment]
需要发送数据之前先打开设备notify，发送数据成功后监听设备notify

**Comment by lanyan520** [comment]
额，建议上传jcenter,项目构建方便

**Comment by dingjikerbo** [comment]
好的，我研究一下

**Comment by dingjikerbo** [comment]
已经搞定了
