### ISSUE TITLE
蓝牙不断开

### ISSUE THREAD

**Issue by cwfzc** [dingjikerbo/BluetoothKit#11]
大神，问个问题，就是我调用这个ClientManager.getClient().disconnect(mac); 方法以后，app已经不再接受蓝牙设备发送的指令，但是蓝牙设备却一直是连接状态，我具体应该怎样去断开蓝牙设备?

**Comment by dingjikerbo** [comment]
不会啊，这个操作会closeGatt，设备怎么会还是连着的

在 2017年1月11日 下午6:38，cwfzc <notifications@github.com>写道：

**Comment by cwfzc** [comment]
我用的三星的Galaxy S4 android5.0.1 测试机，断不开。但是 在华为荣耀6plus android6.0， 则可以断开
