### ISSUE TITLE
ProxyUtils创建代理的实际作用

### ISSUE THREAD

**Issue by ALonelyTraveler** [dingjikerbo/BluetoothKit#15]
您好，我浏览了BluetoothKit的部分源码，在扫描部分中用的ProxyUtils创建代理的实际作用是什么？不是很理解。

**Comment by dingjikerbo** [comment]
http://blog.csdn.net/dingjikerbo/article/details/51261414

**Comment by dingjikerbo** [comment]
所有接口的调用被拦截，统一切换工作线程
