### ISSUE TITLE
Connect failed

### ISSUE THREAD

**Issue by yufu12345** [dingjikerbo/BluetoothKit#16]
Android连接蓝牙设备时，提示Connect Failed。
是否是UUID的问题？

**Comment by dingjikerbo** [comment]
看日志吧，我都打出来了

2017-02-16 10:42 GMT+08:00 yufu12345 <notifications@github.com>:

**Comment by Belolme** [comment]
连接蓝牙设备一旦出现了几次 Connect Failed 之后，就一直提示这个错误，必须关闭蓝牙再打开才行。看日志是提示无法发现 Service 的问题。有没有可能是出现了下面网址提出的情况 http://blog.csdn.net/qq_29984105/article/details/51821837 ？

**Comment by dingjikerbo** [comment]
可能是你同时连的设备太多了吧，最好别超过5个
