### ISSUE TITLE
大神有没有做多设备处理呀

### ISSUE THREAD

**Issue by 354420603** [dingjikerbo/BluetoothKit#20]

**Comment by dingjikerbo** [comment]
具体什么处理

**Comment by 354420603** [comment]
今天用你写这个库写了一个demo，连第一个ble设备的时候没有问题，然后我手动断开再连另一台设备，蓝牙设备显示连上了，但是connect得onResponse回调没有走，然后就在注册的BleConnectStatusListener收到断开提示！再次搜索connect才能连上

**Comment by 354420603** [comment]
没有调用 mClient.disconnect(mac)；就不会出现这种情况

**Comment by 354420603** [comment]
在不调用  mClient.disconnect(currentAddress);的情况下，再次调用mClient.conne（mac）无法连接上

**Comment by WrapOnly** [comment]
@dingjikerbo 大神， 我也在做多设备连接。我处理的方式对多个macAddress调用mClient.connect（mac）连接上之后, 不调用mClient.disconnect方法。请问我这样处理对不对？

**Comment by dingjikerbo** [comment]
建议不要同时连接超过5个设备，否则连接会不稳定，丢包率增加。设备长时间不用的还是断开吧。
