### ISSUE TITLE
在红米手机上版本4.4.4KTU84P扫描蓝牙设备过于频繁时出现BluetoothGatt﹕ android.os.DeadObjectException

### ISSUE THREAD

**Issue by Wberlin** [dingjikerbo/BluetoothKit#27]
扫描蓝牙设备频繁可能出现E/GKILINUX(17741): ##### ERROR : GKIexception: GKIexception(): Task State Table E/GKILINUX(17741): ##### 
E/GKILINUX(17741): ##### ERROR : GKIexception: TASK ID [0] task name [BTU] state [1] 
E/GKILINUX(17741): ##### 
E/GKILINUX(17741): ##### ERROR : GKIexception: TASK ID [1] task name [BTIF] state [1] 
E/GKILINUX(17741): ##### 
E/GKILINUX(17741): ##### ERROR : GKIexception: TASK ID [2] task name [A2DP-MEDIA] state [1] 
E/GKILINUX(17741): ##### 
E/GKILINUX(17741): ##### ERROR : GKIexception: GKIexception 65524 getbuf: out of buffers##### 
E/GKILINUX(17741): ##### ERROR : GKIexception: 
E/GKI_LINUX(17741): **********************

请问怎么才能降低这种情况出现的可能

**Comment by dingjikerbo** [comment]
你是不是在扫到的设备回调里做了耗时操作
