### ISSUE TITLE
registerBluetoothStateListener  这个监听回调不及时，有时候不回调。

### ISSUE THREAD

**Issue by yswheye** [dingjikerbo/BluetoothKit#28]
registerBluetoothStateListener  这个监听回调不及时，有时候不回调。
但是，通过log看到BluetoothKit内部是有状态变化的

**Comment by yswheye** [comment]
状态监听有点乱
这个收到及时
BluetoothReceiver.getInstance().register(new BleConnectStatusChangeListener() {
            @Override
            protected void onConnectStatusChanged(String mac, int status) {
                if (Constants.STATUS_DISCONNECTED == status) {
                   
                } else if (Constants.STATUS_CONNECTED == status) {
                  
                }
            }
        });

ClientManager.getClient().registerConnectStatusListener 收到不及时或收不到

**Comment by yswheye** [comment]
但是BluetoothReceiver.getInstance().register会回调四次

**Comment by dingjikerbo** [comment]
你可能注册了多次。

**Comment by dingjikerbo** [comment]
你确定一下到底是registerBluetoothStateListener不及时还是registerConnectStatusListener不及时
