### ISSUE TITLE
connect回调中的BleGattProfile 没有characters的读写通知属性 

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [dingjikerbo/BluetoothKit#3]
这里的回调都是自定义的uuid相关的封装 但是没有找到对应的读写通知权限
使用起来不是很方便

**Comment by dingjikerbo** [comment]
多谢你的建议，这个会尽快加上

2016-11-17 16:11 GMT+08:00 taoyuanxiaoqi <notifications@github.com>:

**Comment by taoyuanxiaoqi** [comment]
好的 谢谢
