### ISSUE TITLE
这个框架怎么读取经典数据

### ISSUE THREAD

**Issue by xvjialing** [dingjikerbo/BluetoothKit#33]
这个框架怎么读取经典数据

**Comment by xiaojiebudai** [comment]
SearchRequest request = new SearchRequest.Builder()
        .searchBluetoothLeDevice(3000, 3)   // 先扫BLE设备3次，每次3s
        .searchBluetoothClassicDevice(5000) // 再扫经典蓝牙5s
        .searchBluetoothLeDevice(2000)      // 再扫BLE设备2s
        .build();

**Comment by dingjikerbo** [comment]
暂时不支持经典蓝牙的数据读写
