### ISSUE TITLE
如何将byte[] value的值转成整数的心率

### ISSUE THREAD

**Issue by jiao808813** [dingjikerbo/BluetoothKit#34]
public void onNotify(UUID service, UUID character, byte[] value) {
}里面的value值我要转成心率，如何处理？或者如何获得BluetoothGattCharacteristic

**Comment by dingjikerbo** [comment]
看硬件端是如何给心率转成byte[]发送的。BluetoothGattCharacteristic可以在connect的回调里的BleGattProfile中
