### ISSUE TITLE
连接成功后怎么获取BluetoothGatt 对象

### ISSUE THREAD

**Issue by Sabirjan** [dingjikerbo/BluetoothKit#46]
连接成功后怎么获取BluetoothGatt 对象

**Comment by dingjikerbo** [comment]
开发这个库的一个重要初衷就是隐藏BluetoothGatt，内部统一管理。如果需要各种数据或者方法可以以开放接口的形式提供给上层。

**Comment by Sabirjan** [comment]
我的项目里面BluetoothKit用来搜索，连接为主，后面的数据交换用原生API
