### ISSUE TITLE
希望增加一个解除监听的接口

### ISSUE THREAD

**Issue by LeonXtp** [dingjikerbo/BluetoothKit#50]
IBluetoothClient中，增加
void unnotify(String mac, UUID service, UUID character, BleNotifyResponse response)
接口，最后一个参数不同于
BleUnnotifyResponse，
它仅仅是移除设备特征通知的一个监听者，而不是解除对它的所有监听。

**Comment by dingjikerbo** [comment]
这个库是不希望同一个character被notify多次的，如果需要有多个监听者，建议上层自己封装一个Listener Manager。

**Comment by LeonXtp** [comment]
@dingjikerbo 可是库中BluetoothClientImpl类，saveNotifyListener()方法就是将多个监听者保存到了一个List<BleNotifyResponse>中的

**Comment by dingjikerbo** [comment]
目前的逻辑是重复notify会多次注册listener，但是unnotify会清除所有listener，不是对称关系。如果需要是一对一的，建议上层再封装一下，实现起来很简单。
